### Importamos librerias

In [1]:
import numpy as np
import scipy as sp
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

### Importamos los .CSV como Dataframes

In [8]:
DIAGS = pd.read_csv(r"DIAG1.csv", sep="\t", encoding="latin-1")
DIAGS

        ID                                              Glosa  casos
0    A150   TUBERCULOSIS PULMON, CONFIRM.POR HALLAZGO MICR...   1671
1    A151   TUBERCULOSIS DEL PULMON, CONFIRMADA UNICAMENTE...    141
2    A152   TUBERCULOSIS DEL PULMON, CONFIRMADA HISTOLOGIC...    326
3    A153   TUBERCULOSIS DEL PULMON, CONFIRMADA POR MEDIOS...    215
4    A154   TUBERCULOSIS DE GANGLIOS LINFATICOS INTRATORAC...     77
..     ...                                                ...    ...
488  T405                          ENVENENAMIENTO POR COCAINA    485
489  T406   ENVENENAMIENTO POR OTROS NARCOTICOS Y POR LOS ...     28
490  T407             ENVENENAMIENTO POR CANNABIS (DERIVADOS)     75
491  T408            ENVENENAMIENTO POR ACIDO LISERGICO (LSD)     10
492  T409   ENVENENAMIENTO POR OTROS PSICODISLEPTICOS Y PO...     41

[493 rows x 3 columns]

In [3]:
ORIGEN = pd.read_csv(r"PAIS_ORIGEN.csv", sep="\t", encoding="latin-1")
ORIGEN

      ID                                              Glosa   casos
0      0                                                NaN  146388
1      4                                         Afganistán      36
2      5                                    América del Sur       2
3      8                                            Albania       5
4     12                                            Argelia      16
..   ...                                                ...     ...
132  840  Estados Unidos de América Estados Unidos de Am...     363
133  858                                            Uruguay     176
134  862               Venezuela (República Bolivariana de)    1606
135  887                                              Yemen       1
136  890                                         Yugoslavia       4

[137 rows x 3 columns]

In [37]:
id_chile = ORIGEN[ORIGEN['Glosa'].str.contains('Chile', na=False)]['ID'].values
print(f"El ID de Chile es: {id_chile}")

El ID de Chile es: [152]

In [5]:
EGR = pd.read_csv(r"EgresosRM.csv", sep="\t", encoding="latin-1")
EGR

C:\Users\djara\AppData\Local\Temp\ipykernel_32576\3252493891.py:1: DtypeWarning: Columns (6,23,28,30) have mixed types. Specify dtype option on import or set low_memory=False.
  EGR = pd.read_csv(r"EgresosRM.csv", sep="\t", encoding="latin-1")

,ID_PACIENTE,ESTABLECIMIENTO_SALUD,pes,SEREMI,SERVICIO_DE_SALUD,SEXO,FECHA_NACIMIENTO,EDAD_CANT,TIPO_EDAD,EDAD_A_OS,...,DIAG1,DIAG2,INTERV_Q,CODIGO_INTERV_Q_PPAL,PROCED,CODIGO_PROCED_PPAL,AQst1,AQp1,AQst2,AQp2
0,NaN,112100,1,NaN,12.0,2,NaN,NaN,NaN,78,...,I110,NaN,1,NaN,NaN,NaN,L,1.0,NaN,0.0
1,NaN,112100,1,NaN,12.0,1,NaN,NaN,NaN,92,...,J180,NaN,2,NaN,NaN,NaN,F,0.7,M,0.3
2,NaN,114212,0,13.0,NaN,1,NaN,NaN,NaN,33,...,B206,NaN,2,NaN,NaN,NaN,F,0.7,M,0.3
3,NaN,114212,0,13.0,NaN,1,NaN,NaN,NaN,60,...,C780,NaN,2,NaN,NaN,NaN,F,0.7,M,0.3
4,NaN,112100,1,NaN,12.0,1,NaN,NaN,NaN,74,...,E145,NaN,1,NaN,NaN,NaN,F,0.7,M,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433867,63011272E3504E9BE9C14C3682E02691FA4C9E69,112200,0,13.0,NaN,2,1969-04-03,51.0,1.0,51,...,J459,NaN,2,NaN,1.0,501134.0,NaN,NaN,NaN,NaN
1433868,DC23EFA1C98742EE4420AD2F576184076B868A2B,200486,0,13.0,NaN,2,1965-07-09,55.0,1.0,55,...,C189,NaN,1,1802067.0,2.0,NaN,NaN,NaN,NaN,NaN
1433869,C43263803A138A97140CACC365F1867DA791F59E,200050,0,13.0,NaN,1,1941-01-26,79.0,1.0,79,...,J129,NaN,2,NaN,2.0,NaN,NaN,NaN,NaN,NaN
1433870,A3C2A170B275D51A7A2439BD7F27D8487BA4CB86,112530,0,13.0,NaN,2,1945-08-19,74.0,1.0,74,...,C785,NaN,1,1802039.0,1.0,1801006.0,NaN,NaN,NaN,NaN
1433871,DC2305A42BDA2951052C9643A7EE9B3B94C92439,112530,0,13.0,NaN,2,1936-05-14,84.0,1.0,84,...,C180,NaN,1,1802067.0,2.0,NaN,NaN,NaN,NaN,NaN

In [11]:
paisOrigen = EGR['PAIS_ORIGEN']
DIAG1 = EGR['DIAG1']

In [31]:
Datos = pd.DataFrame({'PaisOrigen': paisOrigen, 'DIAG1': DIAG1})
Datos.dropna(inplace=True)
Datos

         PaisOrigen DIAG1
483449          0.0  J189
483450          0.0  C911
483451          0.0  I251
483452          0.0  I251
483453          0.0  J189
...             ...   ...
1433867       152.0  J459
1433868       152.0  C189
1433869       152.0  J129
1433870       152.0  C785
1433871       152.0  C180

[950423 rows x 2 columns]

In [32]:
frec = pd.crosstab(Datos['PaisOrigen'], Datos['DIAG1'])
frec

DIAG1,A150,A151,A152,A153,A154,A155,A156,A157,A158,A159,...,J939,T400,T402,T403,T404,T405,T406,T407,T408,T409
PaisOrigen,,,,,,,,,,,,,,,,,,,,,
0.0,192,3,72,5,13,0,8,9,2,15,...,594,2,7,0,0,179,0,4,0,4
4.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
840.0,0,0,0,0,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
858.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
862.0,17,1,0,2,1,0,7,0,0,0,...,5,0,0,0,0,1,0,0,0,1
887.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
890.0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
prob = frec / frec.values.sum()
prob

DIAG1,A150,A151,A152,A153,A154,A155,A156,A157,A158,A159,...,J939,T400,T402,T403,T404,T405,T406,T407,T408,T409
PaisOrigen,,,,,,,,,,,,,,,,,,,,,
0.0,0.000202,0.000003,0.000076,0.000005,0.000014,0.0,0.000008,0.000009,0.000002,0.000016,...,0.000625,0.000002,0.000007,0.0,0.0,0.000188,0.0,0.000004,0.0,0.000004
4.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
5.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
8.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
12.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
840.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000003,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
858.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
862.0,0.000018,0.000001,0.000000,0.000002,0.000001,0.0,0.000007,0.000000,0.000000,0.000000,...,0.000005,0.000000,0.000000,0.0,0.0,0.000001,0.0,0.000000,0.0,0.000001
887.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000
890.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000